OpenRefine/openrefine.org

documentation.md

Removed the space between [wiki] and (https://github.com/OpenRefine/OpenRefine/wiki/) to fix the sentence appearing on the website as "Please check our \[wiki\] \(https://github.com/OpenRefine/OpenRefine/wiki/) for the complete documentation."

Removed whitespace in markdown link to wiki.

---

index.md

Since Jekyll (and hence GH pages) switched to using kramdown instead of redcarpet for markdown processing, headers *must* have a space between the last `#` and the header text.

Fix markdown H1 in index.md

---

_posts/2018-06-16-Update.md

Also rephrased moving into Software Freedom Conservancy, the OpenRefine Foundation for more clarity.

added hyperlinks for Google News Initiative

---

download.md

Also marked OpenRefine 3.1 as a pre-release in Github since we know now that it has some serious bugs.

Removing download links for OpenRefine 3.1

---

download.md

Hello,
We have been developing [FAIR **metadata** extension](https://github.com/FAIRDataTeam/OpenRefine-metadata-extension) as a successor of legacy [FAIRifier](https://github.com/FAIRDataTeam/FAIRifier). We released [v1.0.0](https://github.com/FAIRDataTeam/OpenRefine-metadata-extension/releases/tag/v1.0.0), so I would like the OpenRefine download page to reflect this...
I also fixed some bad link for BioVel 😄

Add (FAIR) metadata extension

---

_config.yml

It currently defaults to the name of the repository, so you get:
* `openrefine.github.com`
* `Community · openrefine.github.com`
* etc
I have checked that this fixes it on my fork (see https://remram44.github.io/openrefine.github.com/community.html)

Add 'title' to config, to change page titles

---

documentation.md
download.md

Changing most wiki links to the new docs.
There's a link on the Community page that I wanted to ask about before changing: 
https://github.com/OpenRefine/OpenRefine/blob/master/CONTRIBUTING.md
to 
https://docs.openrefine.org/technical-reference/contributing

Website link updates

---

download.md

Hi!
I recently developed a .NET Core client supporting the latest version of OpenRefine. You can take a look in here: https://github.com/ADelRosarioH/OpenRefine.Net.
I would like it to be in the client libraries section of https://openrefine.org/download.html and that's why I'm creating this PR.
I couldn't find any contributing guides for this repo, If there is one, I can close this PR and submit another according to the guide.
Thank you very much!

adds C# .net core client to download page

---

download.md

updated year from 2021 to 2022
Proposed
The latest stable release of OpenRefine 3.5, released on January 26, 2022. 
Current
The latest stable release of OpenRefine 3.5, released on January 26, 2021.

update year to 2022

---

community.md
documentation.md

As proposed on the mailing list, there is enthusiasm to migrate to Discourse for our mailing lists, so this PR changes the website to point to that.

Replace mentions of the Google Groups with links to the Discourse forum

---

docs/technical-reference/writing-extensions.md

Let's drop LESS from the documentation given that core has migrated to CSS and the intent is to stop supporting LESS altogether in the future.

writing extensions: drop mentions of LESS

---

src/pages/community.md

Fixed https://github.com/OpenRefine/openrefine.org/issues/153
Link added to text "getting involved in the development of the tool" in community page so that it redirects to Contributing.md file

Added hyperlink of Contributing.md

---

docs/technical-reference/build-test-run.md

This attempts to:
* give a more readable structure to the build-test-run page
* make more of the content OS-specific using the tab system, so that people only read stuff that is relevant for them
* encourage readers to install dependencies via their package managers (homebrew, linux distribution package managers) rather than manually. Perhaps there are similar solutions for Windows?
* update some commands to their current usage
I plan to do more work on the running section and review the IDE instructions too.

Improve build-test-run page

---

docs/technical-reference/architecture.md

Some parts of this content will need to be adapted for 4.x. Because we are not going to discontinue 3.x immediately I think it would be worth keeping both, and I am thinking of using the tab system (used for operating systems in other pages) to let the reader switch between the two, depending on which architecture they are working with.
Also, quite some comments about the roles of specific Java classes would be better done as proper Javadocs. In 4.x I have been working towards doing more of that, and I hope to be able to publish such javadocs for some core modules at least (such as `refine-model`).

Improve architecture page, updating and filling gaps

---

blog/2023-03-17-project-coordinator.md

This is a draft for a job posting for a project coordinator, following the vacancy of the former project director role.
Given feedback from various people, the advisory committee wants to change the scope of the role to emphasize more of a coordination role, with the intention to give more decision power to the broader community.
Feedback welcome, not just on the language but also on the job's scope and conditions itself.
Pinging @ainali @magdmartin (as advisory committee members) and @Vesihiisi @libcce @lozanaross (as active steering committee members): what do you think of this? If you are not interested in applying yourself, would you be interested in reviewing applicants?

Project manager job posting

---

docs/manual/grelfunctions.md

It looks like the only example of the `cross` function we had in the docs was actually wrong… Can anyone confirm?

Fix cross function example

---

docusaurus.config.js

This adds a link to our Mastodon profile. Sadly, because Mastodon relies on the presence of the `rel="me"` attribute, we need to put explicit HTML in there for profile verification to work. To get the same rendering as other external links, we seemingly need to include this small SVG as well.
There might be better approaches?

Add Mastodon link

---

blog/2023-07-17-version-3-7-4.md

We haven't been doing blog posts about new releases recently, but given that this one fixes a vulnerability I thought it would be worth doing.
It's worth discussing if releases should generally be announced with a blog post (if not all of them, which ones?).
The release process already includes making changes to the website so it does not feel so complicated to also add a blog post in the same go (likely without a PR).

Announcement of version 3.7.4

---

src/pages/index.tsx

This changes the title of the home page from "OpenRefine | OpenRefine" to just "OpenRefine".
For #215.
Adding the tag line seems more involved, but that feels like an improvement already.

Set home page title to just 'OpenRefine'

---

docs/technical-reference/documentation-contributions.md

The current page is out of date (some bits are left from the situation when we had our docs in the main repository).
I tried to update it so that it is also more accessible to folks who are not familiar with the terminal or Git.

Improve page about documentation contributions

---

docs/manual/wikibase/reconciling.md

I think it is useful to include the way to access labels, aliases etc as people often struggle with this. Also I cannot find documented anywhere the way to get Commons sitelinks (adding the wiki on the end was not obvious to me!) so wanted to make sure that was added.

Update reconciling.md to include how to access Commons sitelinks (and labels, aliases, descriptions)

---

sidebars.js

I think the pages in the current "technical reference" category should rather go to the contributing instructions for developers.
This makes it clearer that this content is intended for developers and removes a top-level category, which is quite visible and prominent for users.

Put technical reference inside developer docs

---

static/_headers

This should let anyone fetch the latest OpenRefine version, regardless of their origin. (Funny, this suddenly reads like a social justice campaign…)
For https://github.com/OpenRefine/OpenRefine/issues/6017.
I haven't tested it yet, but according to https://stackoverflow.com/a/62528017/985087 it should do the trick.

Enable CORS headers for /versions.json

---

docs/manual/grelfunctions.md

The documentation did not mention that `days` (or `day`, `d`) could be used to extract the days part of a date.
Also, I used this opportunity to make the table more compact. Is it clear like this that `days`, `day` and `d` are alternative spellings for the same unit?

Make date unit table more compact and add missing 'days' unit

---

docs/manual/grel.md

Fixes #289 
Introduced an 'Operator' section to the GREL page, improving user accessibility to information about operators in GREL.

Added Operator Section to GREL Page 

---

src/releases.js

This prepares the website for the 3.8 release, introducing the Windows installer as one of the possible downloads.
It also drops the Windows zip file without java included [as suggested on the forum](https://forum.openrefine.org/t/releasing-3-8-beta1/1136).
I expect we will want to make the installer the default choice on Windows, but I would only make this shift once we have a stable release in the 3.8 series.
This PR should only be merged when we release 3.8-beta1, since it will otherwise display an empty column in the release table.
See preview of the download page: https://deploy-preview-298--openrefine-website.netlify.app/download

Introduce Windows installer

---

README.md

- Removes mention of Docusaurus version for maintainability
- Updates Yarn installation details
trying to begin to fix #328 with first updating our README to new Yarn syntax from the Yarn installation guide (and Docusaurus install guide).

Update README for new Yarn syntax and installation

---

src/css/custom.css

Fix #331
- Adjusts color ranges for Infirma to meet WCAG AA 4.5:1 contrast ratio
- Adds slightly lighter ranges for `dark` theme to meet as well.

Fix #331 Meet accessible contrast ratio

---

src/pages/download.tsx
src/pages/extensions.md

In the Download page, add an Extensions section below the 'Other platforms and versions' to make the Extensions more visible to users.
Also, update the RDF Transform extension text in the Extensions page.

Add prominent Extensions link in Download page

---

events.json
src/pages/index.tsx

closes #358  
To test the event notification in OpenRefine edit the line 160 of `main/webapp/modules/core/scripts/index.js` from 
```
$.getJSON("https://openrefine.org/versions.json",
``` 
to
```
$.getJSON("https://deploy-preview-361--openrefine-website.netlify.app/versions.json",
```
Results of my local test, since I am in unfamiliar territory, I would prefer if this is double checked by a developer.

#358 update homepage and event notification in OpenRefine

---

docs/manual/wikibase/schema-alignment.md

- as a result of this issue:  https://github.com/OpenRefine/OpenRefine/issues/6798

Add tip admonition for Wikidata Help:Dates

---

blog/2024-10-21-announcing-version-3-8-3.md

Given that we are going to patch severe vulnerabilities in 3.8.3, I think it could be worth pre-announcing the release. I've picked 24th October 2024 as release date, but it can be changed of course.

Security announcement for 3.8.3

---

docs/manual/running.md

As per instructions in the web page https://github.com/OpenRefine/OpenRefine/wiki/Google-Extension#missing-credentials.
This seems to be missing.
Regards, Antoine

Update running.md to add Google Data JVM preferences

---

docs/manual/running.md

Fixes #201
Update running.md to use -Drefine.interface and Update running.md to use -Drefine.host, or REFINE_INTERFACE and REFINE_HOST.

Update running.md to use -Drefine.interface

---

docs/manual/grelfunctions.md

this is the PR for issue #376 
The documentation is correct now after comparing the correct field letters here: 
https://docs.oracle.com/javase/8/docs/api/java/time/format/DateTimeFormatter.html

fix documentation for toString() data fromat codes in grelfunctins.md #376

---

docusaurus.config.js
package.json

PR for Issue https://github.com/OpenRefine/openrefine.org/issues/276
This PR addresses the addition of the lastmod field to the sitemap. After applying these changes, the generated sitemap.xml (accessible at /sitemap.xml) will look as follows:

added sitemap to docusaurus.config.js file and also added missing serve script in the package.json#276

---

src/pages/usage.md

I refreshed the statistics as of December 3, 2024, in preparation for the year-end blog post. 
I changed the format of the Contribution Statistics graph to represent the average number of contributors per year because the previous graph did not display all the values correctly. For the time series, Mermaid required each x value to be explicitly listed, which made the x-axis too crowded when displaying monthly data points. I also tried using a rolling 6-month average, but the axis was still cluttered. I believe that the yearly average is sufficient to demonstrate the trends in contributions over time.

refresh statistic on usage page

---

docusaurus.config.js
src/pages/mission_vision.md

This PR adds the results of the work to clarify OpenRefine's Mission, Vision, and Values following the project completed in 2024. see the [related discussion on the forum](https://forum.openrefine.org/t/feedback-request-on-openrefines-draft-vision-mission-values/1619/8). 
The integration in the website was previously discussed in #291 and on the [forum](https://forum.openrefine.org/t/requesting-feedback-documenting-openrefine-community-handbooks/1224/2)

add mission vision value page

---

docs/manual/running.md

Adding in Automating section a link to OR’s CLI from Felix Lohmeier.

Add a link to OR’s CLI in the Automating section

---

blog/2024-11-25-openrefine-developer-role.md
src/pages/community.md
src/pages/index.tsx
src/pages/mission_vision.md

adding mission and vision on home and community page 

---

docs/technical-reference/translating-ui.md

Various fixes to the translating-ui page.

Update translation instructions

---

src/pages/funding.md

Archived Wikimedia-23 and EOSS-Diversity grant (both completed Dec 31, 2024). I will add the final report for the Diversity report once ready
Set the Wikimedia General Fund application as unsuccessful as per [Jan 30, 2025 conversation.](https://forum.openrefine.org/t/january-30-2025-advisory-call-only/2045)

update funding page with completed and unsuccessful grant application

---

docs/manual/expressions.md

- this clarifies a few differences and uses italics for emphasis and introduces the notion that our Regex engine is Java-based, but the syntax is Javascript-based.

Clarify Regular expression syntax paragraphs

---

docs/manual/running.md

Update running.md to Launch OpenRefine from the Terminal to make work in MacOS 14.7 Sonoma.

Update running.md to Launch OpenRefine from the Terminal on MacOS

---

docs/manual/running.md

Update running.md to had usage of the tool `defaults` for MacOS to make configuration easier.
Regards, Antoine

Update running.md adding the tool `defaults` for MacOS

---

docs/manual/exploring.md
docs/manual/grelfunctions.md

- Fixes https://github.com/OpenRefine/OpenRefine/issues/6009

Add admonition about Date functions now using UTC

---

releases.json

Now that version 3.9.3 has build artifacts attached to the GitHub release, I am updating the releases JSON file to point to the new latest version.

Set version to 3.9.3

---

docs/technical-reference/version-release-process.md

This PR adds a new section to address the process for creating a patch release, which relies on cherry-picking commits in `master` rather than building a new branch. While the steps are largely the same, I thought it would helpful to differentiate between the patch version release process and the major/minor release process.

Update release process notes with patch version steps

---

docs/manual/grelfunctions.md

The `phonetic` function accepts a limited list of algorithm names. To avoid confusion the names in the documentation now match the expected names by the function.

List phonetic algorithms with their correct names
