OpenRefine/openrefine.org

- governance.md
Sorry if I did this incorrectly. I'm kind of new to Git/Github/contributing to projects, but I love OpenRefine and was interested in the governance model. I figured I would just clean up this document a little bit while I was reading through it. The changes are quite minor.
> Update governance.md with spelling/grammar fixes.

- download.md
> Fix plurals (typos?).

- download.md
- added client libraries from the wiki
- restructured links to GitHub releases
> update downloads page

- download.md
And removed older DERI RDF Extension 0.8 for OpenRefine 2.5
> Added Stuart Kenny's working RDF Extension

- _layouts/index.html
- community.md
- documentation.md
- download.md
Series of minor improvements and update. 
- Added new distribution and fork on the download page (OntoRefine and Fairifier)
- Added new tutorials on the documentation page 
- Clean up and Update Contributors page
- Add list of translation available  #22
See list of commits for details.
> Minor improvements 

- download.md
I've also created a PR for the RDF Extension author to update his readme.md to make it easier for folks new to Github on how to get to releases page.
This should help everyone going forward with getting to the latest RDF Extension release if they don't know how.
> Change URL for RDF Extension for ease

- download.md
this will help those unfamiliar with Github to directly see the downloads presented on the README.md and click and download.
> Link directly to README.md for RDF extension

- _posts/2019-11-02_wikidatacon_award.md
Adds a news post for the WikidataCon award
> Add post for WikidataCon award

- _posts/2020-02-22-outreachy-gsoc.md
Announces that we participate in Outreachy and GSoC.
> Add Outreachy-GSoC blog post

- _posts/2020-04-23-documentation-hire.md
The call can be discussed on the developer mailing list too.
> Blog post for documentation job posting

- _posts/2020-05-04-outreachy-gsoc-projects.md
Small post to announce selected interns and projects. Feel free to tweak.
> Announce selected interns

- privacy.md
> fix: privacy is not listed in the sidebar

- community.md
- adds Gitter chat link
- adds dev mailing list
- adds missing ending paragraph tag
> Add dev mailing list to Community page and cleanup

- download.md
"Latter" means second of the two options, "former" would mean first, which I'm assuming is the intended meaning.
> "Latter" -> "former"

- _posts/2021-11-10-Advisory-committee-member.md
- _posts/2021-12-12-Advisory-committee-member.md
> First draft of advisory committee post

- _posts/2021-12-12-Advisory-committee-member.md
- A few small spelling corrections and copyedits
- Unify capitalization of the committee names
- Unify punctuation after bullet points
- Add a few hyperlinks
> Copyedits to 2021-12-12-Advisory-committee-member.md

- download.md
The maintainer of LodRefine has indicated that this project has been deprecated.
> This app has not been actively maintained for years now due to many reasons (I switched job, company was sold etc). Unfortunately, I don’t have time nor interest to continue with the development, but some cool and smart people are still working on Open Refine: https://github.com/OpenRefine/OpenRefine
> 
> Please note that all the extensions are available as separate repositories, but they are outdated, too due to similar reasons as stated above.
> 
> Please visit OpenRefine project to check on the latest development of this amazing tool and the extensions they already integrated into it.
https://github.com/sparkica/LODRefine
> Deprecate LodRefine

- _posts/2022-09-30-windows-macos-packaging.md
Very much interested in feedback on this, in particular:
* what do you think of this application procedure? Is it ok to send the proposals (including price) in public or should they be directed to some more private address (like hiring@openrefine.org?)
* is it okay not to announce a total budget for this? Perhaps people will not really know the scale of the effort.
* any other issues that should be in the scope of this effort?
* the github issues are a bit messy - perhaps they should be reformulated to be a bit more specific and well written-up?
Closes #116.
> Blog post for packaging announcement.

- blog/2013-11-05-using_openrefine.md
- blog/2014-08-29-2014-survey-results.md
- blog/2015-01-26-Mapping-OpenRefine-ecosystem.md
- blog/2018-06-16-Update.md
- blog/2018-07-16-2018-survey-results.md
- blog/2020-02-20-2020-survey-results.md
- blog/2022-06-28-2022-survey-results.md
This should fix the image links in the blog posts as per #130
The images should ideally have alt tags added but I've left these out for now to prioritising the link fix
> Fix image links

- versioned_docs/version-3.6/manual/grelfunctions.md
fixed line 345 to reflect new changes of parameters according to issue # 5394
> issue #5394 (contd.) -- Updated line 345 of grelfunctions.md

- versioned_docs/version-3.6/technical-reference/writing-extensions.md
For https://github.com/OpenRefine/OpenRefine/pull/5312
> Add documentation for cell rendering extension point

- blog/2022-12-30-eoss5.md
Here is a draft blog post to announce the EOSS5 grant.
> EOSS5 announcement blog post

- docs/manual/installing.md
> Wrong extensions link on documentation

- docs/manual/installing.md
- docs/manual/starting.md
Fixes another wrong extensions url
> Fixes #176 

- docs/technical-reference/architecture.md
- docs/technical-reference/clustering-in-depth.md
- docs/technical-reference/openrefine-api.md
Collection of small fixes in preparation for larger improvements
> Stylistic improvements to technical docs

- docs/manual/running.md
Somehow it does not render correctly at the moment:
> Fix JVM preferences table

- docs/technical-reference/contributing.md
I tried expanding the "Your first pull request" guide to be a bit more explicit and helpful.
> Improve contributing.md page

- src/css/custom.css
- src/pages/download.tsx
Closes #162.
To test this, you can install a browser extension to change your user agent, pretending that you are using a different operating system, to see the effect.
> Advertise other distributions.

- docs/technical-reference/build-test-run.md
Updated Maven documentation for https://github.com/OpenRefine/OpenRefine/issues/5484.
> Updated Maven documentation

- docusaurus.config.js
- src/pages/community.md
Removed StackOverflow and Gitter cards/links from the community page
Fixes #195
> fix(community): remove stackoverflow and gitter cards

- docs/manual/running.md
Changes the refine.bat Windows usage statement for https://github.com/OpenRefine/OpenRefine/issues/5359.
> Changes for the refine.bat windows usage statement

- src/css/custom.css
- src/pages/community.md
fix for logo openrefine is magic #207
https://github.com/OpenRefine/openrefine.org/issues/207
> fix for logo openrefine is magic #207

- docs/technical-reference/reconciliation-api.md
This adds a few pointers to resources about the protocol. It could be expanded a lot more, but that's a start.
> Improve documentation of the reconciliation API

- blog/2023-03-17-project-coordinator.md
I think we have enough applicants already.
> Close call for applicants for project manager position

- blog/2023-05-05-outreachy-interns.md
Here is a blog post to announce the internships. Let me know if you want anything changed (or feel free to edit yourself, via the "Files changed" tab).
cc @lozanaross @Lydiaofficial @ayushrai206
> Blog post for 2023 Outreachy interns

- docs/manual/running.md
Add clustering choice limit to Running - Preference Doc
I have no idea what the next release version is, so I just followed what was above and put v3.8
Related code change: https://github.com/OpenRefine/OpenRefine/pull/5847
> Add clustering choice limit

- docs/technical-reference/build-test-run.md
Follow-up for https://github.com/OpenRefine/OpenRefine/pull/5916
> Document minimum version of dev dependencies

- docs/manual/grelfunctions.md
> Add language code details for toDate()

- docs/technical-reference/build-test-run.md
In the interest of avoiding manual reformatting.
> Mention style configuration in intelliJ

- blog/2023-09-12-version-3-7-5.md
Blog post similar to version 3.7.4.
> Announce version 3.7.5

- docusaurus.config.js
- releases.json
- src/pages/post_download.tsx
- src/plugins/docusaurus-versionsjson-plugin/index.js
- src/releases.js
> Expose release information in /versions.json

- blog/2023-12-16-barcamp-venue-options.md
I think it's worth making a blog post to reach out to folks who would be able to see this but don't watch the forum actively.
> Add blog post to ask for BarCamp venues

- docs/technical-reference/Introduction.md
I made a small grammatical change to the introduction for design contributors, it's a test for my own learning.
> Test grammatical change

- sidebars.js
> Remove duplicate sidebar entry for GREL functions

- blog/2024-02-22-barcamp.md
Edits welcome :)
Preview: https://deploy-preview-302--openrefine-website.netlify.app/blog/2024/02/22/barcamp
> Add blog post to announce the BarCamp's date

- blog/2024-03-14-gsoc.md
> Add blog post to announce our participation to GSoC 2024

- blog/2024-04-05-barcamp-registration-opens.md
Edits welcome, feel free to just make changes directly.
> Add blog post to announce the barcamp registration

- src/pages/privacy.md
For https://github.com/OpenRefine/OpenRefine/pull/6511
> Add section about update notifications

- events.json
- src/plugins/docusaurus-versionsjson-plugin/index.js
This will be used to notify users of particular events happening around the project, such as user surveys, for
https://github.com/OpenRefine/OpenRefine/issues/6290.
> Add 'events' field in versions.json

- docs/technical-reference/build-test-run.md
For https://github.com/OpenRefine/OpenRefine/pull/6526
> Update minimum Node version to 20

- docs/technical-reference/writing-extensions.md
For https://github.com/OpenRefine/OpenRefine/pull/6484.
> Point to standalone repo for sample extension and clean up

- blog/2024-05-01-gsoc-intern.md
To be filled with the selected contributor after the announcement.
> Draft GSoC 2024 selection announcement

- blog/2024-06-01-barcamp-registration.md
Draft of blog post to announce the initial schedule of the BarCamp.
> Blog post for the barcamp kick-off

- src/pages/funding.md
our application was not selected for funding. This PR update the grant status.
> DEF grant - update funding.md

- docs/manual/grelfunctions.md
> Update Get documentation, fixes #341

- src/pages/usage.md
I am updating the forum and contributors statistics in preparation of the [Wikimedia Community Fund](https://forum.openrefine.org/t/grant-opportunity-wikimedia-community-fund/1728)
> Update forum and contribution statistics

- src/pages/usage.md
This PR follows #381 and fix the date for the forum statistic.
> Update usage.md correct date for the forum statistic 

- events.json
- src/pages/index.tsx
- src/pages/usage.md
Closes #384 
Remove the notification from the homepage and in-app notification
> Close 2024 survey

- src/pages/funding.md
[Related forum discussion](https://forum.openrefine.org/t/grant-opportunity-wikimedia-community-fund/1728)
> Update funding.md with 2024 Wikimedia Foundation

- docs/manual/grelfunctions.md
> Fix toTitleCase documentation

- docs/manual/installing.md
- package.json
As per discussion in fix: #373 
I had created a very minor first draft in case to reflect my understanding towards the issue. I will need a little more discussion on this but please review this changes.
Before: 
After: 
Thank you, I know this is not enough but for an understanding demonstration I am raising this PR.
> This is the first draft in hope of getting green flag to continue this or not

- blog/2024-10-30-openrefine-developer-role.md
- blog/2024-11-25-openrefine-developer-role.md
> OpenRefine-Dev-Community-Role

- src/pages/extensions.md
As a follow-up to un-bundling the Gdata extension (https://github.com/OpenRefine/OpenRefine/pull/6958), here's a proposal to add it to our directory.
> Add gdata extension

- docs/technical-reference/version-release-process.md
- put changeable portion of mvn command at the end
- remove obsolete link to wiki
- add a note about draft -> publish flakiness
> Update release process based on recent run

- releases.json
- src/pages/whats_new.md
> Update releases.json to 3.8.7

- docs/technical-reference/code-contributions.md
As per @wetneb comment https://github.com/OpenRefine/OpenRefine/pull/6736#issuecomment-2263514370 we strive to have 1 test class per tested class, so let's document that better.
> [DOCS] Update code-contributions.md

- src/css/custom.css
- src/pages/post_download.tsx
> Improved PostDownload Page (#371)

- docs/technical-reference/clustering-in-depth.md
fixes #421 
It was a small change, but I saw that it was open for a week so raising the PR.
Thank you :)
> Fixed for Broken link

- docs/manual/running.md
Update running.md to add the new preference to the Preferences table.
> Add the notification.status preference to the Preferences table

- docs/manual/running.md
Update running.md to add the proxy to JVM preferences
> Update running.md adding proxy to JVM preferences

- blog/2025-02-11-FilesExtension.md
> FilesExtension - blog post update

- blog/2025-02-13-version-3-9-0.md
@magdmartin feel free to directly make changes as you see fit and merge.
Preview: https://deploy-preview-431--openrefine-website.netlify.app/blog/2025/02/13/version-3-9-0
> Blog post to announce 3.9

- blog/2025-02-21-AIExtension.md
- src/pages/extensions.md
AI Extension blog post
Updated OR Version for Files Extension to 3.9
> AI Extension blog post

- blog/2020-04-23-documentation-hire.md
- blog/2020-08-28-cfp-contributor-experience.md
- blog/2021-07-07-OpenRefine-SDC-developer.md
- blog/2021-11-05-Project-director.md
- blog/2021-12-12-Advisory-committee-member.md
- blog/2023-03-17-project-coordinator.md
- blog/2023-06-08-Advisory-committee-member.md
- blog/2023-08-25-reproducibility-designer.md
- blog/2024-11-25-openrefine-developer-role.md
- blog/2025-02-13-call-for-advisory-committee-members.md
Following [April 17, 2025 AC meeting](https://forum.openrefine.org/t/april-17-2024-advisory-committee/2252#p-6671-advisory-committee-recruitment-6), I am adding "Open" and "Closed" statuses to the titles of each blog post to clearly indicate each position's current status.
> Updating Job Posting With Status

- docs/technical-reference/version-release-process.md
Small tweaks to make the documentation of the release process clearer.
> Release process improvements

- src/pages/usage.md
Update usage and contribution statistics in preparation for the [NLNet grant application](https://forum.openrefine.org/t/2025-nlnet-ngi-zero-commons-fund/2381)
> Update usage and contribution statistic. 

- blog/2025-06-10-OpenRefine-2025-Barcamp.md
Update the barcamp page with details regarding the event.
> Update blog with barcamp details

- docs/manual/cellediting.md
> Update links to technical reference in manual
